### ISSUE TITLE
Filtering issue with SeaMonkey & AMO

### ISSUE THREAD

**Issue by graciecat** [JustOff/modify-http-response#2]
I installed the extension in SeaMonkey 2.48 for Linux (Ubuntu 14.04.5). I used the filter given me (from [here](https://github.com/JustOff/moon-tester-tool/issues/4)).

`[["addons.cdn.mozilla.net",["/impala-min\\.js/",["$(\"#downloadAnyway\").attr","return;$(\"#downloadAnyway\").attr","/a.addClass\\(\"concealed\"\\);/gi","a.addClass(\"download\");a.addClass(\"download\").removeClass(\"add\").find(\"span\").text(\"Download Now\");"]]]]
`

It is supposed to unlock SeaMonkey-incompatible extensions from AMO. On SeaMonkey pages it removes the gray box and gives access to the green download box, in the cases where the listed SeaMonkey version is below that of my browser (v. 2.48).

Before MHR
https://s6.postimg.org/eatt6aai9/Modify-http-response_00.png

After MHR
https://s6.postimg.org/afqf3prch/Modify-_HTTP-response_01.png

However, on the Firefox pages, we still see the green "For Firefox-only" box, and so the XPI cannot be downloaded

Before & after MHR
https://s6.postimg.org/9eq6elacx/Modify-http-response_02.png

**Comment by JustOff** [comment]
It seems Mozilla updated AMO scripts, here is the updated rule:
```
[["addons.cdn.mozilla.net",["/impala-min\\.js/",["app==\"firefox\"){","app==\"firefox\"){return;","/a.addClass\\(\"concealed\"\\);/gi","a.addClass(\"download\");a.addClass(\"download\").removeClass(\"add\").find(\"span\").text(\"Download Now\");"]]]]
```
