### ISSUE TITLE
replace <script> tags

### ISSUE THREAD

**Issue by spyrosmas** [JustOff/modify-http-response#4]
How to replace <script> whatever </script> tags with nothing?
I'm trying several strings from regex101.com with no results and end up thinking I had something wrong.

**Comment by JustOff** [comment]
Could you give me a specific example of the page and the script you want to replace?

**Comment by spyrosmas** [comment]
lets say a large news site like in.gr which is full of scripts inside the main page or the microsoft site, how to remove all those <script....</script> with nill?

**Comment by JustOff** [comment]
If you want to block all scripts you better use [NoScript](https://noscript.net/), [uMatrix](https://github.com/gorhill/uMatrix/wiki/How-to-block-1st-party-scripts-everywhere-by-default) or [uBlock](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering), as Modify HTTP Response can be useful only when you need to change or remove some particular element (or script).

**Comment by spyrosmas** [comment]
I know and already use the NoScript and the uBlock now-days, but when I save a page to the disk it occupies a lot more space because of those embedded scripts. Those adblock techniques only stop scripts from execute... Also some of them try to execute when I launch the saved htm page in my browser and is time consuming to find and replace all those script tags by hand although I do it form time to time.

**Comment by SAYATHEB** [comment]
`/<script>?.+?<\/script>/g`

**Comment by spyrosmas** [comment]
@SAYATHEB my complete string is ``[["in.gr",["/",["/<script>?.+?<\\/script>/g"," "]]]]`` and does not work. All <script tags are left untouched :-(

**Comment by SAYATHEB** [comment]
The host should be ```www.in.gr```. You can check for that in the console ```location.host```.

**Comment by JustOff** [comment]
`.` does not match line breaks, so in order to catch multiline patterns you should use `[\s\S]` instead:

`[["www.in.gr",["/^/",["/<script[\\s\\S]*?<\\/script>/g",""]]]]`
